/**
 * Report generator — markdown report from InvestigationReport.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { InvestigationReport } from '@ai-debug/shared';

const AGENT_VERSION = '7.0.0';

const formatDuration = (ms: number): string => {
  const seconds = Math.round(ms / 1_000);
  const minutes = Math.floor(seconds / 60);
  const remaining = seconds % 60;
  return minutes > 0 ? `${minutes.toString()}m ${remaining.toString()}s` : `${seconds.toString()}s`;
};

const buildHeader = (report: InvestigationReport): string[] => [
  `# 🔍 Investigation Report`,
  '',
  `**URL:** ${report.url}`,
  `**Severity:** ${report.severity}`,
  `**Duration:** ${formatDuration(report.durationMs)}`,
  `**Date:** ${report.timestamp}`,
];

const buildSummary = (report: InvestigationReport): string[] => [
  '', '---', '', '## Summary', '', report.summary,
];

const buildRootCause = (report: InvestigationReport): string[] => [
  '', '---', '', '## Root Cause', '', report.rootCause,
];

const buildCodeLocation = (report: InvestigationReport): string[] => {
  if (report.codeLocation === null) return [];
  return ['', '---', '', '## Code Location', '',
    `**File:** \`${report.codeLocation.file}\``,
    `**Line:** ${report.codeLocation.line.toString()}`,
    ...(report.codeLocation.snippet !== undefined && report.codeLocation.snippet !== '' ? ['', '```typescript', report.codeLocation.snippet, '```'] : []),
  ];
};

const buildSuggestedFix = (report: InvestigationReport): string[] => {
  if (report.suggestedFix === null) return [];
  return ['', '---', '', '## Suggested Fix', '',
    report.suggestedFix.explanation,
  ];
};

const buildReproSteps = (report: InvestigationReport): string[] => {
  if (report.reproSteps.length === 0) return [];
  return ['', '---', '', '## Repro Steps', '',
    ...report.reproSteps.map((step, i) => `${(i + 1).toString()}. ${step}`),
  ];
};

const MAX_EVIDENCE_DISPLAY = 15;

const buildEvidence = (report: InvestigationReport): string[] => {
  if (report.evidence.length === 0) return [];
  return ['', '---', '', `## Evidence (${report.evidence.length.toString()} items)`, '',
    ...report.evidence.slice(0, MAX_EVIDENCE_DISPLAY).map((ev) => `- **[${ev.type}]** ${ev.description}`),
  ];
};

const buildNetworkFindings = (report: InvestigationReport): string[] => {
  if (report.networkFindings.length === 0) return [];
  return ['', '---', '', '## Network Findings', '',
    ...report.networkFindings.map((f) => `- ${f}`),
  ];
};

const buildHypotheses = (report: InvestigationReport): string[] => {
  if (report.hypotheses.length === 0) return [];
  return ['', '---', '', '## Hypotheses', '',
    '| ID | Hypothesis | Status |',
    '|---|---|---|',
    ...report.hypotheses.map((h) => `| ${h.id} | ${h.text} | **${h.status}** |`),
  ];
};

const buildConclusion = (report: InvestigationReport): string[] => {
  if (report.conclusion === '') return [];
  return ['', '---', '', '## Conclusion', '', report.conclusion];
};

const buildFooter = (): string[] => [
  '', '---', '',
  `*Generated by AI Debug Agent v${AGENT_VERSION} — Single-Loop Architecture*`,
];

const buildMarkdown = (report: InvestigationReport): string => [
  ...buildHeader(report),
  ...buildSummary(report),
  ...buildRootCause(report),
  ...buildCodeLocation(report),
  ...buildSuggestedFix(report),
  ...buildReproSteps(report),
  ...buildEvidence(report),
  ...buildNetworkFindings(report),
  ...buildHypotheses(report),
  ...buildConclusion(report),
  ...buildFooter(),
].join('\n');

const generateFileName = (report: InvestigationReport): string => {
  const urlPart = new URL(report.url).host;
  const datePart = new Date(report.timestamp).toISOString().slice(0, 10);
  return `${datePart}-${urlPart}.md`;
};

export const saveReport = async (
  report: InvestigationReport,
  reportsDir?: string,
): Promise<string> => {
  const dir = reportsDir ?? './debug-reports';
  await mkdir(dir, { recursive: true });
  const fileName = generateFileName(report);
  const filePath = join(dir, fileName);
  await writeFile(filePath, buildMarkdown(report), 'utf-8');
  return filePath;
};
