/**
 * Report generator — markdown report from InvestigationReport.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { InvestigationReport, Hypothesis } from '@ai-debug/shared';

const REPORTS_DIR = './debug-reports';
const AGENT_VERSION = '4.0.0';

const formatDuration = (ms: number): string => {
  const seconds = Math.round(ms / 1_000);
  const minutes = Math.floor(seconds / 60);
  const remaining = seconds % 60;
  return minutes > 0 ? `${minutes.toString()}m ${remaining.toString()}s` : `${seconds.toString()}s`;
};

const statusEmoji = (status: Hypothesis['status']): string => {
  const map: Record<Hypothesis['status'], string> = {
    confirmed: '✅', refuted: '❌', partial: '⚠️', testing: '🔄', untested: '⏳',
  };
  return map[status];
};

const buildHeader = (report: InvestigationReport): string[] => [
  `# 🔍 Investigation Report`,
  '',
  `**URL:** ${report.url}`,
  `**Severity:** ${report.severity}`,
  `**Duration:** ${formatDuration(report.durationMs)}`,
  `**Date:** ${report.timestamp}`,
];

const buildRootCause = (report: InvestigationReport): string[] => [
  '', '---', '', '## Root Cause', '', report.rootCause,
];

const buildCodeLocation = (report: InvestigationReport): string[] => {
  if (report.codeLocation === null) return [];
  const lines = ['', '---', '', '## Code Location', '',
    `**File:** \`${report.codeLocation.originalFile}\``,
    `**Line:** ${report.codeLocation.originalLine.toString()}`,
  ];
  if (report.codeLocation.codeSnippet !== '') {
    lines.push('', '```typescript', report.codeLocation.codeSnippet, '```');
  }
  return lines;
};

const buildDataFlow = (report: InvestigationReport): string[] => {
  if (report.dataFlow === '') return [];
  return ['', '---', '', '## Data Flow', '', '```', report.dataFlow, '```'];
};

const buildSuggestedFix = (report: InvestigationReport): string[] => {
  if (report.suggestedFix === null) return [];
  return ['', '---', '', '## Suggested Fix', '',
    `**\`${report.suggestedFix.file}:${report.suggestedFix.line.toString()}\`**`, '',
    report.suggestedFix.explanation,
  ];
};

const buildHypotheses = (report: InvestigationReport): string[] => {
  if (report.hypotheses.length === 0) return [];
  return [
    '', '---', '', '## Hypotheses Investigated', '',
    '| ID | Statement | Result | Confidence |',
    '|---|---|---|---|',
    ...report.hypotheses.map((h) =>
      `| ${h.id} | ${h.statement} | ${statusEmoji(h.status)} ${h.status.charAt(0).toUpperCase() + h.status.slice(1)} | ${h.confidence.toFixed(2)} |`,
    ),
  ];
};

const buildReproSteps = (report: InvestigationReport): string[] => {
  if (report.reproSteps.length === 0) return [];
  return ['', '---', '', '## Repro Steps', '',
    ...report.reproSteps.map((step, i) => `${(i + 1).toString()}. ${step}`),
  ];
};

const buildEvidence = (report: InvestigationReport): string[] => {
  if (report.evidence.length === 0) return [];
  return ['', '---', '', `## Evidence (${report.evidence.length.toString()} items)`, '',
    ...report.evidence.slice(0, 15).map((ev) => `- **[${ev.type}]** ${ev.description}`),
  ];
};

const buildAssumptions = (report: InvestigationReport): string[] => {
  if (report.assumptions.length === 0) return [];
  return ['', '---', '', '## Assumptions', '',
    ...report.assumptions.map((a) => `- ${a}`),
  ];
};

const buildFooter = (): string[] => [
  '', '---', '',
  `*Generated by AI Debug Agent v${AGENT_VERSION} — Investigation-First Architecture*`,
];

const buildMarkdown = (report: InvestigationReport): string => [
  ...buildHeader(report),
  ...buildRootCause(report),
  ...buildCodeLocation(report),
  ...buildDataFlow(report),
  ...buildSuggestedFix(report),
  ...buildHypotheses(report),
  ...buildReproSteps(report),
  ...buildEvidence(report),
  ...buildAssumptions(report),
  ...buildFooter(),
].join('\n');

const generateFileName = (report: InvestigationReport): string => {
  const urlPart = new URL(report.url).pathname.replace(/\//g, '-').slice(0, 30);
  const datePart = new Date(report.timestamp).toISOString().slice(0, 10);
  return `${urlPart}-${datePart}.md`;
};

export const saveReport = async (
  report: InvestigationReport,
  reportsDir?: string,
): Promise<string> => {
  const dir = reportsDir ?? REPORTS_DIR;
  await mkdir(dir, { recursive: true });
  const fileName = generateFileName(report);
  const filePath = join(dir, fileName);
  await writeFile(filePath, buildMarkdown(report), 'utf-8');
  return filePath;
};
